version: '3.8'
services:
  dev:
    build: .
    image: hope-pg
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.git:/root/.git
      - .:/workspaces:cached
      - .:/com.docker.devenvironments.code
      #
 
